LibraryManagmentSystem/LibraryManagmentSystem.MVC/Controllers/BooksController.cs
using AutoMapper;
using LibraryManagmentSystem.Application.Commands;
using LibraryManagmentSystem.Application.Queries;
using LibraryManagmentSystem.Infrastructure.DAL;
using LibraryManagmentSystem.MVC.Extensions;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PagedList;

namespace LibraryManagmentSystem.MVC.Controllers;

public class BooksController : Controller
{
    private readonly IMediator _mediator;
    private readonly IMapper _mapper;
    private readonly LibraryDbContext _dbContext;
    public BooksController(IMediator mediator,IMapper mapper, LibraryDbContext dbContext)
    {
        _mediator = mediator;
        _mapper = mapper;
        _dbContext = dbContext;
    }

    public async Task<IActionResult> Index(int? page, int? pageSize)
    {
        int pageIndex = page ?? 1;
        int pageSizeValue = pageSize ?? 10;
        
        var books = await _mediator.Send(new GetAllBooksQuery());
        var pagedBooks = books.ToPagedList(pageIndex, pageSizeValue);
        return View(pagedBooks);
    }

    public async Task<IActionResult> ScienceFictionBooks()
    {
        string type = "SciFi";
        var dto = await _mediator.Send(new GetBooksByTypeQuery(type));
        return View(dto);
    }

    public async Task<IActionResult> ThrillerBooks()
    {
        string type = "Thriller";
        var dto = await _mediator.Send(new GetBooksByTypeQuery(type));
        return View(dto);
    }

    public async Task<IActionResult> LiteraryFictionBooks()
    {
        string type = "LiteraryFiction";
        var dto = await _mediator.Send(new GetBooksByTypeQuery(type));
        return View(dto);
    }

    public async Task<IActionResult> RomanceBooks()
    {
        string type = "Romance";
        var dto = await _mediator.Send(new GetBooksByTypeQuery(type));
        return View(dto);
    }

    public async Task<IActionResult> BiographiesBooks()
    {
        string type = "Biographies";
        var dto = await _mediator.Send(new GetBooksByTypeQuery(type));
        return View(dto);
    }

    public async Task<IActionResult> ActionsBooks()
    {
        string type = "Action_Adventure";
        var dto = await _mediator.Send(new GetBooksByTypeQuery(type));
        return View(dto);
    }

    [Authorize(Roles = "Admin")]
    public IActionResult CreateBook()
    {
        PublishedHousesDropDownList();
        return View();
    }

    [Authorize(Roles = "Admin")]
    [HttpPost]
    public async Task<IActionResult> CreateBook(CreateBookCommand command)
    {
        if (!ModelState.IsValid)
        {
            return View(command);
        }
        await _mediator.Send(command);

        this.SetNotification("success", $"Added book: {command.Name}");

        return RedirectToAction(nameof(Index));
    }

    [Route("Books/{bookName}/Details")]
    public async Task<IActionResult> BookDetails(string bookName)
    {
        var dto = await _mediator.Send(new GetBookDetailsQuery(bookName));
        return View(dto);
    }

    [Route("Books/{bookName}/Edit")]
    public async Task<IActionResult> EditBook(string bookName)
    {
        PublishedHousesDropDownList(); 
        var dto = await _mediator.Send(new GetBookDetailsQuery(bookName));
        EditBookCommand command = _mapper.Map<EditBookCommand>(dto);
        return View(command);
    }

    [HttpPost]
    [Route("Books/{bookName}/Edit")]
    public async Task<IActionResult> EditBook(string bookName,EditBookCommand command)
    {
        if (!ModelState.IsValid)
        {
            return View(command);
        }
        
        await _mediator.Send(command);
        return RedirectToAction(nameof(Index));
    }

    [Authorize(Roles = "Admin")]
    [Route("Books/{bookName}/Delete")]
    public async Task<IActionResult> DeleteBook(string bookName)
    {
        var dto = await _mediator.Send(new GetBookDetailsQuery(bookName));
        DeleteBookCommand command = _mapper.Map<DeleteBookCommand>(dto);
        return View(command);
    }

    [HttpDelete]
    [Authorize(Roles = "Admin")]
    [Route("Books/{bookName}/Delete")]
    public async Task<IActionResult> DeleteBook(string bookName, DeleteBookCommand command)
    {
        if (!ModelState.IsValid)
        {
            return View(command);
        }

        await _mediator.Send(command);
        return RedirectToAction(nameof(Index));
    }

    [Authorize]
    public IActionResult CreateBookReservation()
    {
        BooksDropDownList();
        return View();
    }


    [HttpPost]
    [Authorize]
    public async Task<IActionResult> CreateBookReservation(CreateReservationCommand command)
    {
        if (!ModelState.IsValid)
        {
            return View(command);
        }
        await _mediator.Send(command);

        return RedirectToAction(nameof(Index));
    }

    private void BooksDropDownList()
    {
        List<SelectListItem> books = new SelectList(_dbContext.Books, "BookId", "Name").ToList();
        ViewBag.Books = books;
    }

    private void PublishedHousesDropDownList()
    {
        List<SelectListItem> publishedHouses = new SelectList(_dbContext.PublishedHouses, "PublishedHouseId", "PublishedHouseName").ToList();
        ViewBag.PublishedHouses = publishedHouses;
    }
}

LibraryManagmentSystem/LibraryManagmentSystem.MVC/Controllers/DocumentsController.cs
using iTextSharp.text.pdf;
using iTextSharp.text;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using LibraryManagmentSystem.Infrastructure.DAL;
using Microsoft.Data.SqlClient;
using System.Data;

namespace LibraryManagmentSystem.MVC.Controllers
{
    public class DocumentsController : Controller
    {
        private readonly LibraryDbContext _dbContext;
        private readonly IConfiguration _configuration;
        public DocumentsController(LibraryDbContext dbContext, IConfiguration configuration)
        {
            _dbContext = dbContext;
            _configuration = configuration;

        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult GenerateBookListPDF()
        {
            Document document = new Document();
            MemoryStream memoryStream = new MemoryStream();
            PdfWriter writer = PdfWriter.GetInstance(document, memoryStream);

            document.Open();
            var data = _dbContext.Books.ToList();

            PdfPTable table = new PdfPTable(3);
            PdfPCell headerCell = new PdfPCell(new Phrase("Books List"));
            headerCell.Colspan = 4;
            headerCell.HorizontalAlignment = Element.ALIGN_CENTER;
            headerCell.BackgroundColor = BaseColor.CYAN;
            table.AddCell(headerCell);

            var boldFont = FontFactory.GetFont(FontFactory.HELVETICA_BOLD, 12);
            table.AddCell(new PdfPCell(new Phrase("Name", boldFont)));
            table.AddCell(new PdfPCell(new Phrase("Author", boldFont)));
            table.AddCell(new PdfPCell(new Phrase("Genre", boldFont)));

            foreach (var item in data)
            {
                table.AddCell(new PdfPCell(new Phrase(item.Name)));
                table.AddCell(new PdfPCell(new Phrase(item.Author)));
                table.AddCell(new PdfPCell(new Phrase(item.Genre)));
            }

            document.Add(table);
            document.Close();

            byte[] bytes = memoryStream.ToArray();
            memoryStream.Dispose();

            return File(bytes, "application/pdf", "BookList.pdf");
        }

        public IActionResult GenerateBookingListPDF()
        {
            Document document = new Document();
            MemoryStream memoryStream = new MemoryStream();
            PdfWriter writer = PdfWriter.GetInstance(document, memoryStream);

            document.Open();
            var data = _dbContext.Reservations
                .Where(x => x.StatusId == 3)
                .ToList();

            PdfPTable table = new PdfPTable(5);
            PdfPCell headerCell = new PdfPCell(new Phrase("Completed Booking List"));
            headerCell.Colspan = 5;
            headerCell.HorizontalAlignment = Element.ALIGN_CENTER;
            headerCell.BackgroundColor = BaseColor.CYAN;
            table.AddCell(headerCell);

            var boldFont = FontFactory.GetFont(FontFactory.HELVETICA_BOLD, 12);
            table.AddCell(new PdfPCell(new Phrase("ReservationId", boldFont)));
            table.AddCell(new PdfPCell(new Phrase("BookId", boldFont)));
            table.AddCell(new PdfPCell(new Phrase("ReservationStart", boldFont)));
            table.AddCell(new PdfPCell(new Phrase("ReservationEnd", boldFont)));
            table.AddCell(new PdfPCell(new Phrase("UserId", boldFont)));

            foreach (var item in data)
            {
                table.AddCell(new PdfPCell(new Phrase(item.ReservationId.ToString())));
                table.AddCell(new PdfPCell(new Phrase(item.BookId.ToString())));
                table.AddCell(new PdfPCell(new Phrase(item.ReservationStart.ToString())));
                table.AddCell(new PdfPCell(new Phrase(item.ReservationEnd.ToString())));
                table.AddCell(new PdfPCell(new Phrase(item.UserId.ToString())));
            }

            document.Add(table);
            document.Close();

            byte[] bytes = memoryStream.ToArray();
            memoryStream.Dispose();

            return File(bytes, "application/pdf", "CompletedBookingList.pdf");
        }

    }
}

LibraryManagmentSystem/LibraryManagmentSystem.MVC/Controllers/HomeController.cs
using LibraryManagmentSystem.MVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace LibraryManagmentSystem.MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Contact()
        {
            return View();
        }

        public IActionResult Gallery()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

LibraryManagmentSystem/LibraryManagmentSystem.MVC/Controllers/ReservationsController.cs
using AutoMapper;
using LibraryManagmentSystem.Application.Commands;
using LibraryManagmentSystem.Application.Queries;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace LibraryManagmentSystem.MVC.Controllers
{
    public class ReservationsController : Controller
    {
        private readonly IMediator _mediator;
        private readonly IMapper _mapper;

        public ReservationsController(IMediator mediator, IMapper mapper)
        {
            _mediator = mediator;
            _mapper = mapper;
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            var reservations = await _mediator.Send(new GetAllReservationsQuery());
            return View(reservations);
        }

        [Authorize]
        public async Task<IActionResult> YoursReservations()
        {
            var reservations = await _mediator.Send(new GetUsersReservationQuery());
            return View(reservations);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> BookingInCurrentMonth()
        {
            var reservations = await _mediator.Send(new GetMonthBookingQuery());
            return View(reservations);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> BookingInCurrentDay()
        {
            var reservations = await _mediator.Send(new GetDayBookingQuery());
            return View(reservations);
        }

        [Authorize(Roles = "Admin")]
        [Route("Reservations/{reservationId}/Details")]
        public async Task<IActionResult> ReservationDetails(Guid reservationId)
        {
            var dto = await _mediator.Send(new GetReservationDetailsQuery(reservationId));
            return View(dto);
        }

        [Authorize(Roles = "Admin")]
        [Route("Reservations/{reservationId}/Edit")]
        public async Task<IActionResult> EditReservationStatus(Guid reservationId)
        {
            var dto = await _mediator.Send(new GetReservationDetailsQuery(reservationId));
            EditReservationCommand command = _mapper.Map<EditReservationCommand>(dto);
            return View(command);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [Route("Reservations/{reservationId}/Edit")]
        public async Task<IActionResult> EditReservationStatus(Guid reservationId, EditReservationCommand command)
        {
            if (!ModelState.IsValid)
            {
                return View(command);
            }

            await _mediator.Send(command);
            return RedirectToAction(nameof(Index));
        }

        [Authorize]
        [Route("Reservations/{reservationId}/RentalExtend")]
        public async Task<IActionResult> ExtendRental(Guid reservationId)
        {
            var dto = await _mediator.Send(new GetReservationDetailsQuery(reservationId));
            RentalExtendCommand command = _mapper.Map<RentalExtendCommand>(dto);
            return View(command);
        }

        [Authorize]
        [HttpPost]
        [Route("Reservations/{reservationId}/RentalExtend")]
        public async Task<IActionResult> ExtendRental(Guid reservationId, RentalExtendCommand command)
        {
            if (!ModelState.IsValid)
            {
                return View(command);
            }

            await _mediator.Send(command);
            return RedirectToAction(nameof(YoursReservations));
        }

    }
}

LibraryManagmentSystem/LibraryManagmentSystem.MVC/Controllers/UsersController.cs
using AutoMapper;
using LibraryManagmentSystem.Application.Queries;
using LibraryManagmentSystem.Domain.Entities;
using MediatR;
using Microsoft.AspNetCore.Mvc;

namespace LibraryManagmentSystem.MVC.Controllers
{
    public class UsersController : Controller
    {
        private readonly IMediator _mediator;
        private readonly IMapper _mapper;
        public UsersController(IMediator mediator, IMapper mapper)
        {
            _mediator = mediator;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            var users = await _mediator.Send(new GetAllUsersQuery());
            return View(users);
        }

        [Route("Users/{username}/Details")]
        public async Task<IActionResult> UserDetails(string username)
        {
            var dto = await _mediator.Send(new GetUserDetailsQuery(username));
            return View(dto);
        }
    }
}

LibraryManagmentSystem/LibraryManagmentSystem.MVC/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact Page";
}

<div class="container">
        <div class="row">
            <div class="col-sm-6">
                <div class="card">
                    <div class="card-body">
                        <h2 class="card-title" style="text-align:center">Reception hours:</h2>
                        <h5 style="text-align:center">Monday: 9.00 - 18.00</h5>
                        <h5 style="text-align:center">Tuesday: 9.00 - 18.00</h5>
                        <h5 style="text-align:center">Wednesday: 9.00 - 18.00</h5>
                        <h5 style="text-align:center">Thursday: 9.00 - 18.00</h5>
                        <h5 style="text-align:center">Friday: 9.00 - 18.00</h5>
                    </div>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="card">
                    <div class="card-body">
                        <h2 class="card-title" style="text-align:center">Address:</h2>
                        <h5 style="text-align:center">Email: contact@librarysystem.pl</h5>
                        <h5 style="text-align:center">Phone Number: +48 22 467 16 67</h5>
                        <h5 style="text-align:center">Phone Number: +48 602 567 325</h5>
                        <h5 style="text-align:center">Address: ul. Konopnickiej 45a</h5>
                        <h5 style="text-align:center">Postal Code: 35-210 Rzeszów</h5>
                    </div>
                </div>
            </div>
            <div class="col-sm-12" style="margin-top: 5%">
                <div class="card">
                    <div class="card-body">
                        <h2 class="card-title" style="text-align:center">You have a question ?</h2>
                        <h2 class="card-title" style="text-align:center">Write to as email: <b>contact@librarysystem.pl</b></h2>
                    </div>
                </div>
            </div>
            <div class="col-sm-12" style="margin-top: 5%">
                <div class="card">
                    <div class="card-body text-center">
                    <img src="~/images/logo.png" alt="Logo" style="width: 200px; height: auto; text-align:center;"/>
                    </div>
                </div>
            </div>
        </div>

    </div>

LibraryManagmentSystem/LibraryManagmentSystem.MVC/Views/Home/Gallery.cshtml
@{
    ViewData["Title"] = "Contact Page";
}

<div class="container">
    <div class="row">
        <div class="col-lg-4 col-md-12 mb-4 mb-lg-0">
            <img src="~/images/library.jpg"
                 class="w-100 shadow-1-strong rounded mb-4"
                 alt="Library One" />

            <img src="~/images/library2.jpg"
                 class="w-100 shadow-1-strong rounded mb-4"
                 alt="Library Two" />
        </div>

        <div class="col-lg-4 mb-4 mb-lg-0">
            <img src="~/images/library3.jpg"
                 class="w-100 shadow-1-strong rounded mb-4"
                 alt="Library Three" />
            <img src="~/images/library4.jpg"
                 class="w-100 shadow-1-strong rounded mb-4"
                 alt="Library 4" />
        </div>

        <div class="col-lg-4 mb-4 mb-lg-0">
            <img src="~/images/library5.jpg"
                 class="w-100 shadow-1-strong rounded mb-4"
                 alt="Library 5" />
            <img src="~/images/library6.jpg"
                 class="w-100 shadow-1-strong rounded mb-4"
                 alt="Library 6" />
        </div>
    </div>
</div>

LibraryManagmentSystem/LibraryManagmentSystem.MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome in Library Managment System!</h1>
</div>
@if(!User.IsInRole("Admin"))
{
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img class="d-block w-100" src="~/images/library3.jpg" alt="First slide">
                <div class="carousel-caption d-none d-md-block">
                    <h5>Discover fantastic books!</h5>
                </div>
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="~/images/library5.jpg" alt="Second slide">
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
}
@if(User.IsInRole("Admin"))
{
   <nav class ="navbar bg-white">
        <ul class ="nav navbar-nav">
            <li class ="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Reservations" asp-action="Index"><i class="bi bi-window"> Reservations List</i></a>
            </li>
            <li class ="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Reservations" asp-action="BookingInCurrentMonth"><i class="bi bi-calendar3"> Booking in this Month</i></a>
                <a class="nav-link text-dark" asp-area="" asp-controller="Reservations" asp-action="BookingInCurrentDay"><i class="bi bi-calendar3"> Booking in Current Day</i></a>
            </li>
            <li class ="nav-item">
                  <a class="nav-link text-dark" asp-area="" asp-controller="Books" asp-action="Index"><i class="bi bi-book"> Books List</i></a>
            </li>
            <li class ="nav-item">
                  <a class="nav-link text-dark" asp-area="" asp-controller="Books" asp-action="CreateBook"><i class="bi bi-database-add"> Add New Book</i></a>
            </li>
             <li class ="nav-item">
                  <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index"><i class="bi bi-person-circle"> User Managment</i></a>
            </li>
            <li class ="nav-item">
                  <a class="nav-link text-dark" asp-area="" asp-controller="Documents" asp-action="Index"><i class="bi bi-filetype-pdf">Documents Generator</i></a>
            </li>
            <li class ="nav-item">
                  <a class="nav-link text-dark" asp-area="" asp-controller="PublishedHouses" asp-action="CreatePublishedHouse"><i class="bi bi-house-add-fill">Add New Publish House</i></a>
            </li>
             <li class ="nav-item">
                  <a class="nav-link text-dark" asp-area="" asp-controller="PublishedHouses" asp-action="Index"><i class="bi bi-house">Published House List</i></a>
            </li>
        </ul>
    </nav>
}

LibraryManagmentSystem/LibraryManagmentSystem.MVC/Views/Home/NoAccess.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>You have no access to this operation</h1>
<a class="btn btn-primary" asp-area="" asp-controller="Home" asp-action="Index">Back to Main Page</a>